language: node_js

node_js:
  - node # will use latest node

cache:
  directories:
    - ~/.npm
    - node_modules

script: # the build step
  - npm run lint
  - npm run build
  - $(npm bin)/cypress run --record

after_success:
  - npm run deploy

notifications:
  email: # only receive email when the build status changes (someone broke the build!)
    on_failure: change
    on_success: change
